modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/TeamMetallurgy/Masonry/issues"
license="All Rights Reserved" # Todo: Consider a better license such as MIT, LGPL, BSD, Creative Commons, etc... :(

[[mods]]
modId="masonry"
version="${file.jarVersion}"
displayName="Masonry"
displayURL="https://www.curseforge.com/minecraft/mc-mods/masonry"
#logoFile="examplemod.png"
credits="Shadowclaimer - Artist/Designer, Vequinox - Programmer"
authors="Shadowclaimer, Vequinox, Paint_Ninja"
description='''
Masonry is a mod that adds more decorative block options to the Stonecutter's recipe list, as well as a few craftable blocks.
'''

[[dependencies.masonry]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.masonry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.16.3]"
    ordering="NONE"
    side="BOTH"