modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/TeamMetallurgy/Masonry/issues"

[[mods]]
modId="masonry"
version="${file.jarVersion}"
displayName="Masonry"
displayURL="https://www.curseforge.com/minecraft/mc-mods/masonry"
#logoFile="examplemod.png"
credits="Shadowclaimer - Artist/Designer, Vequinox - Programmer"
authors="Shadowclaimer, Vequinox"
description='''
Masonry is a mod that adds more decorative block options to the Stonecutter's recipe list, as well as a few craftable blocks.
'''

[[dependencies.masonry]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.masonry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"